services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - ./init-db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - /var/lib/postgresql/data
  
  go-server:
    build: .
    ports:
      - "8081:8081"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: mysecretpassword
      DB_NAME: postgres
    depends_on:
      - db
      # - ollamaq

volumes:
  # ollama_data:
  postgres_data:
